# Generated by Django 6.0.5 on 2026-06-29 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_libro_portada'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='portada',
            field=models.ImageField(blank=True, null=True, upload_to='portadas/'),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/'),
        ),
    ]
